# Generated by Django 3.2.18 on 2023-06-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona'),
        ),
        migrations.AddField(
            model_name='det_compras',
            name='cabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cab_compras'),
        ),
        migrations.AddField(
            model_name='det_compras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto'),
        ),
        migrations.AddField(
            model_name='cab_compras',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona'),
        ),
    ]
