# Generated by Django 3.2.18 on 2023-06-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20230617_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
