# Generated by Django 3.2.18 on 2023-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20230617_1600'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
